version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: crowdfunding_postgres
    ports:
      - '6500:5432'
    volumes:
      - crowdfundingDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: crowdfunding_redis
    ports:
      - '6379:6379'
    volumes:
      - crowdfundingRedisDB:/data
volumes:
  crowdfundingDB:
  crowdfundingRedisDB:


